branches:
  only:
    - master
    - work

language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages: ['g++-5']
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install:
    - eval "${MATRIX_EVAL}"
script:
 - ./configure -b maintain  && cd build/maintain && make Experimental


