branches:
  only:
    - master
    - work
    - travis

language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
          update-alternatives:
            - install /usr/bin/gcc gcc /usr/bin/gcc-6 50
            - install /usr/bin/g++ g++ /usr/bin/g++-6 50
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config gcc; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config g++; fi
    - gcc --version
script:
 - ./configure -b maintain -P -DSOLID_TEST_NONE=TRUE -P -DSOLID_TEST_UTILITY=TRUE && cd build/maintain/examples/utility/workpool/ && make -j4


