branches:
  only:
    - master
    - work
    - travis

language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages: ['g++-5']
          sources: &sources
            - ubuntu-toolchain-r-test
      env: [ CXX_COMPILER=g++-5, C_COMPILER=gcc-5]
      
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: [ CXX_COMPILER=clang++, C_COMPILER=clang]

script:
 - ./configure -b maintain -P -DCMAKE_C_COMPILER=$C_COMPILER -P -DCMAKE_CXX_COMPILER=$CXX_COMPILER && cd build/maintain/solid/utility/test && make -j2 && make test 


