branches:
  only:
    - master
    - work

language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages: ['g++-6']
          sources:
            - ubuntu-toolchain-r-test
          update-alternatives:
            - install /usr/bin/gcc gcc /usr/bin/gcc-6 1
            - install /usr/bin/g++ g++ /usr/bin/g++-6 1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install:
    - eval "${MATRIX_EVAL}"
script:
 - ./configure -b maintain -P -DSOLID_TEST_NONE=TRUE -P -DSOLID_TEST_UTILITY=TRUE && cd build/maintain && make Experimental


